name: Compile and generate PDF

on:
  push:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Get a copy of the Checkout
      uses: actions/checkout@4.2.2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@3.4.2
      with:
        dotnet-version: '9.0.x'

    - name: install dependencies
      run: dotnet restore

    - name: Compile
      run: dotnet build --no-restore

  create-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output:dir: pdfs
          build_html: true
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: pdfs
      
